/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.invensense.android.hardware;

public class glyphapi {
  public static int MLAddGlyph(int GlyphID) {
    return glyphapiJNI.MLAddGlyph(GlyphID);
  }

  public static int MLBestGlyph(short[] finalGesture) {
    return glyphapiJNI.MLBestGlyph(finalGesture);
  }

  public static int MLSetGlyphSpeedThresh(int speed) {
    return glyphapiJNI.MLSetGlyphSpeedThresh(speed);
  }

  public static int MLStartGlyph() {
    return glyphapiJNI.MLStartGlyph();
  }

  public static int MLStopGlyph() {
    return glyphapiJNI.MLStopGlyph();
  }

  public static int MLGetGlyph(int index, int[] x, int[] y) {
    return glyphapiJNI.MLGetGlyph(index, x, y);
  }

  public static int MLGetGlyphLength(short[] length) {
    return glyphapiJNI.MLGetGlyphLength(length);
  }

  public static int MLClearGlyph() {
    return glyphapiJNI.MLClearGlyph();
  }

  public static int MLLoadGlyphs(short[] libraryData) {
    return glyphapiJNI.MLLoadGlyphs(libraryData);
  }

  public static int MLStoreGlyphs(short[] libraryData, short[] length) {
    return glyphapiJNI.MLStoreGlyphs(libraryData, length);
  }

  public static int MLSetGlyphProbThresh(int prob) {
    return glyphapiJNI.MLSetGlyphProbThresh(prob);
  }

  public static int MLGetLibraryLength(short[] length) {
    return glyphapiJNI.MLGetLibraryLength(length);
  }

}
