/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.invensense.android.hardware;

class glyphapiJNI {
  static {
      /*
       * Load the library.  If it's already loaded, this does nothing.
       */
      System.loadLibrary("gesture_manager_jni");
  }
  
  public final static native int MLAddGlyph(int jarg1);
  public final static native int MLBestGlyph(short[] jarg1);
  public final static native int MLSetGlyphSpeedThresh(int jarg1);
  public final static native int MLStartGlyph();
  public final static native int MLStopGlyph();
  public final static native int MLGetGlyph(int jarg1, int[] jarg2, int[] jarg3);
  public final static native int MLGetGlyphLength(short[] jarg1);
  public final static native int MLClearGlyph();
  public final static native int MLLoadGlyphs(short[] jarg1);
  public final static native int MLStoreGlyphs(short[] jarg1, short[] jarg2);
  public final static native int MLSetGlyphProbThresh(int jarg1);
  public final static native int MLGetLibraryLength(short[] jarg1);
}
